#!/bin/bash
# Trusted source archive updater. Executed after explicit confirmation inside LUB.
set -euo pipefail
[[ $# -eq 5 ]] || exit 64
TARGET="$1"; ARCHIVE="$2"; PARENT_PID="$3"; INSTALL_HELPER="$4"; PERMANENT_TARGET="$5"
[[ "$TARGET" == *.app && -d "$TARGET" && "$ARCHIVE" == *.zip && -f "$ARCHIVE" ]] || exit 65
[[ ! -L "$TARGET" && ! -L "$ARCHIVE" ]] || exit 65
DEST_DIR="$(dirname "$TARGET")"
[[ -w "$DEST_DIR" ]] || { echo 'App installation folder is not writable' >&2; exit 73; }
STAGE="$(mktemp -d "${TMPDIR:-/tmp/}lub-source-XXXXXXXX")"
LOG="$HOME/Library/Logs/Local Update Bridge/self-update-$(date +%Y%m%d-%H%M%S).log"
mkdir -p "$(dirname "$LOG")"
exec >>"$LOG" 2>&1
trap 'rm -rf -- "$STAGE"' EXIT
printf 'Source update start: %s\n' "$(date)"
/usr/bin/python3 - "$ARCHIVE" "$STAGE" <<'PY'
import os, pathlib, sys, zipfile
archive, dest = sys.argv[1:]
with zipfile.ZipFile(archive) as z:
    entries=z.infolist()
    if not entries or len(entries)>5000: raise SystemExit('Invalid archive entry count')
    total=0
    for item in entries:
        name=item.filename
        p=pathlib.PurePosixPath(name)
        if p.is_absolute() or not name or '\\' in name or any(x in ('..','') for x in p.parts): raise SystemExit('Unsafe archive path')
        if (item.external_attr >> 16) & 0o170000 == 0o120000: raise SystemExit('Archive symlink not permitted')
        total+=item.file_size
        if total>250_000_000: raise SystemExit('Archive exceeds 250MB uncompressed limit')
    for item in entries:
        output=pathlib.Path(dest, *pathlib.PurePosixPath(item.filename).parts)
        if item.is_dir(): output.mkdir(parents=True,exist_ok=True); continue
        output.parent.mkdir(parents=True,exist_ok=True)
        with z.open(item) as src, open(output,'wb') as dst:
            import shutil
            shutil.copyfileobj(src,dst)
PY
SOURCE="$(find "$STAGE" -name build-macos.sh -type f -print -quit)"
[[ -n "$SOURCE" && -f "$(dirname "$SOURCE")/LocalUpdateBridge.swift" ]] || { echo 'No LUB source project detected in ZIP' >&2; exit 66; }
SOURCE_DIR="$(dirname "$SOURCE")"
# Never execute the archive's own build script. Use the deterministic bundled build recipe.
command -v swiftc >/dev/null && command -v iconutil >/dev/null || { echo 'Xcode Command Line Tools required' >&2; exit 69; }
mkdir -p "$STAGE/compiled.app/Contents/MacOS" "$STAGE/compiled.app/Contents/Resources"
/usr/bin/swiftc -parse-as-library -O -framework SwiftUI -framework AppKit -framework CryptoKit -framework UserNotifications "$SOURCE_DIR/LocalUpdateBridge.swift" -o "$STAGE/compiled.app/Contents/MacOS/LocalUpdateBridge"
/usr/bin/iconutil -c icns "$SOURCE_DIR/branding/LUBIcon.iconset" -o "$STAGE/compiled.app/Contents/Resources/LUBIcon.icns"
cp "$SOURCE_DIR/branding/LUBIcon.png" "$STAGE/compiled.app/Contents/Resources/LUBIcon.png"
if [[ -f "$SOURCE_DIR/branding/LUBMark.png" ]]; then
    cp "$SOURCE_DIR/branding/LUBMark.png" "$STAGE/compiled.app/Contents/Resources/LUBMark.png"
fi
cp "$SOURCE_DIR/cli/lub" "$STAGE/compiled.app/Contents/Resources/lub"
cp "$SOURCE_DIR/lub-self-update.sh" "$STAGE/compiled.app/Contents/Resources/lub-self-update.sh"
cp "$SOURCE_DIR/lub-source-update.sh" "$STAGE/compiled.app/Contents/Resources/lub-source-update.sh"
chmod +x "$STAGE/compiled.app/Contents/Resources/"*.sh "$STAGE/compiled.app/Contents/Resources/lub"
# Read version metadata from the release rather than writing a fixed version.
VERSION="1.5.0"; BUILD="150"
if [[ -f "$SOURCE_DIR/lub-self-update.json" ]]; then
    RELEASE_INFO="$(/usr/bin/python3 - "$SOURCE_DIR/lub-self-update.json" <<'PYMETA'
import json, re, sys
with open(sys.argv[1], encoding='utf-8') as f: m=json.load(f)
if m.get('bundleID')!='org.lub.LocalUpdateBridge' or m.get('kind')!='lub-source-release':
    raise SystemExit('Not a LUB source release')
version=m.get('version',''); build=m.get('build')
if not re.fullmatch(r'[0-9]+(?:\.[0-9]+){1,3}', version) or not isinstance(build,int) or build<1:
    raise SystemExit('Invalid release version')
print(version,build)
PYMETA
)" || exit 66
    read -r VERSION BUILD <<< "$RELEASE_INFO"
fi
# Bundle metadata generated by our trusted recipe, not arbitrary archive metadata.
cat > "$STAGE/compiled.app/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleExecutable</key><string>LocalUpdateBridge</string>
<key>CFBundleIdentifier</key><string>org.lub.LocalUpdateBridge</string>
<key>CFBundleName</key><string>Local Update Bridge</string>
<key>CFBundleDisplayName</key><string>Local Update Bridge</string>
<key>CFBundleIconFile</key><string>LUBIcon</string>
<key>CFBundlePackageType</key><string>APPL</string>
<key>CFBundleShortVersionString</key><string>${VERSION}</string>
<key>CFBundleVersion</key><string>${BUILD}</string>
<key>LSMinimumSystemVersion</key><string>14.0</string>
</dict></plist>
PLIST
/usr/bin/plutil -lint "$STAGE/compiled.app/Contents/Info.plist"
for i in {1..90}; do kill -0 "$PARENT_PID" 2>/dev/null || break; sleep 1; done
if kill -0 "$PARENT_PID" 2>/dev/null; then echo 'LUB did not exit; no change made' >&2; exit 75; fi
# Existing installer stages a copy, swaps bundles, retains backup, and relaunches.
# Install into a stable project location, not the Downloads or DerivedData app.
# Preserve the downloaded source archive and source project: they are not temporary artifacts.
[[ "$PERMANENT_TARGET" == "$HOME/Documents/App projects/Update Bridge/Local Update Bridge.app" ]] || exit 65
mkdir -p "$(dirname "$PERMANENT_TARGET")"
/bin/bash "$INSTALL_HELPER" "$PERMANENT_TARGET" "$STAGE/compiled.app" "$PARENT_PID" "$TARGET"
printf 'Self-update finished. Log: %s\n' "$LOG"
